public class B {

    Account acc1 = new Account();
    Account acc2 = new Account();

    Contact con1 = new Contact();
    Contact con2 = new Contact();
    Contact con3 = new Contact();

    Opportunity opp1 = new Opportunity();
    Opportunity opp2 = new Opportunity();

    Lead leadSample = new Lead();
    Lead leadTest = new Lead();

    // randomcheck123
    //helloo
    // buildtriggerflow
    // samplecommentline
    // testdataentry
}
